// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarfaceAPI.Data;

#nullable disable

namespace WarfaceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241230191700_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarfaceAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanId")
                        .HasColumnType("integer");

                    b.Property<string>("ClanName")
                        .HasColumnType("text");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WarfaceAPI.Models.PlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<int?>("PveDeath")
                        .HasColumnType("integer");

                    b.Property<float?>("PveKd")
                        .HasColumnType("real");

                    b.Property<int?>("PveKills")
                        .HasColumnType("integer");

                    b.Property<int?>("PvpDeath")
                        .HasColumnType("integer");

                    b.Property<float?>("PvpKd")
                        .HasColumnType("real");

                    b.Property<int?>("PvpKills")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlayersStats");
                });

            modelBuilder.Entity("WarfaceAPI.Models.PlayerStatsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<int?>("PveDeath")
                        .HasColumnType("integer");

                    b.Property<float?>("PveKd")
                        .HasColumnType("real");

                    b.Property<int?>("PveKills")
                        .HasColumnType("integer");

                    b.Property<int?>("PvpDeath")
                        .HasColumnType("integer");

                    b.Property<float?>("PvpKd")
                        .HasColumnType("real");

                    b.Property<int?>("PvpKills")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlayerStatsHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
